### ISSUE TITLE
Where can I find the list of muted scripts?

### ISSUE THREAD

**Issue by dandv** [spy-js/spy-js#46]
I'm using Spy.js via the PyCharm plugin. After right-clicking on a file to mute it, I accidentally entered a too broad pattern, and now I see "All files of the event are muted".

Where can I access the list of muted files?

**Comment by dandv** [comment]
Found it, it's under the Filter icon.

![image](https://cloud.githubusercontent.com/assets/33569/5622440/943f18b4-94f8-11e4-9fd2-cf1975a4582d.png)

Worth a mention in the README?

**Comment by ArtemGovorov** [comment]
Added the link to the full official documentation to the README. The full documentation available [here](https://www.jetbrains.com/webstorm/help/spy-js-capture-exclusions-dialog.html?search=spy). You can also read more about exclusions in the [blog post](http://blog.jetbrains.com/webstorm/2014/04/spy-js-webstorm-secret-service/#settings).
